# Image metadata and config.
# Ideally, the Node.js version should match what we use on CI.
# See `executors > default-executor` in `.circleci/config.yml`.
FROM mcr.microsoft.com/devcontainers/typescript-node

RUN npm install -g @angular/cli

EXPOSE 4200