export enum EstadoSolicitacaoType {
  ABERTA = 'ABERTA',
  ORCADA = 'ORCADA',
  REJEITADA = 'REJEITADA',
  APROVADA = 'APROVADA',
  REDIRECIONADA = 'REDIRECIONADA',
  AGUARDANDO_PAGAMENTO = 'AGUARDANDO_PAGAMENTO',
  PAGA = 'PAGA',
  FINALIZADA = 'FINALIZADA',
}
